@pipeline_id = content_pipeline_1
@index_id = page_content_1

### verify connectivity
GET {{OPENSEARCH_BASE_URL}}
Authorization: Basic admin:{{OPENSEARCH_INITIAL_ADMIN_PASSWORD}}

### set up pipeline
PUT {{OPENSEARCH_BASE_URL}}/_ingest/pipeline/{{pipeline_id}}
Authorization: Basic admin:{{OPENSEARCH_INITIAL_ADMIN_PASSWORD}}
Content-Type: application/json

{
  "description": "This pipeline processes website page data",
  "processors": [
    {
      "html_strip": {
        "field": "content",
        "target_field": "content_cleaned"
      }
    },
    {
      "trim": {
        "field": "content_cleaned"
      }
    },
    {
      "lowercase": {
        "field": "content_cleaned"
      }
    }
  ]
}

### simulate the pipeline
POST {{OPENSEARCH_BASE_URL}}/_ingest/pipeline/{{pipeline_id}}/_simulate
Authorization: Basic admin:{{OPENSEARCH_INITIAL_ADMIN_PASSWORD}}
Content-Type: application/json

{
  "docs": [
    {
      "_source": {
        "content": "<p>Sample content with <strong>HTML</strong> tags.</p>"
      }
    }
  ]
}

### delete index if it exists
DELETE {{OPENSEARCH_BASE_URL}}/{{index_id}}

### create index
PUT {{OPENSEARCH_BASE_URL}}/{{index_id}}
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "canonical_url": {
        "type": "keyword"
      },
      "content": {
        "type": "text"
      },
      "content_cleaned": {
        "type": "text"
      },
      "last_scraped": {
        "type": "date"
      },
      "last_updated": {
        "type": "date"
      },
      "title": {
        "type": "text"
      },
      "description": {
        "type": "text"
      },
      "etag": {
        "type": "keyword"
      }
    }
  }
}
