apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "kagi-principal-project.camlittle.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: web-server
                port:
                  name: http-main
  tls:
    - hosts:
        - "kagi-principal-project.camlittle.com"
      secretName: kagi-principal-project-tls
---
{{- $name := .Values.email | required ".Values.email is required." -}}

## NOTE: there may be a circular dependency with the cert-manager helm.
# If you see
# > Error: UPGRADE FAILED: ...no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
# then you may need to comment this out, install/upgrade, then uncomment and upgrade.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
