name: Docker build/publish

on:
  push:
    branches:
      - main

concurrency:
  group: main-build
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: do-prod
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log into github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build web_server image
        run: |
          docker build -t web_server \
            --build-arg="VERSION=${{ github.sha }}" \
            --build-arg="WORKSPACE=web_server" \
            --build-arg="WORKSPACE_DIR=web_server" \
            --label "runnumber=${GITHUB_RUN_ID}" \
            -f Dockerfile \
            .

      - name: Push web_server image to github registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/web_server
          docker tag web_server $IMAGE_ID:latest
          docker tag web_server $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ github.sha }}

      - name: Build page_scraper image
        run: |
          docker build -t page_scraper \
            --build-arg="VERSION=${{ github.sha }}" \
            --build-arg="WORKSPACE=page_scraper" \
            --build-arg="WORKSPACE_DIR=crawlers/page_scraper" \
            --label "runnumber=${GITHUB_RUN_ID}" \
            -f Dockerfile \
            .

      - name: Push page_scraper image to github registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/page_scraper
          docker tag page_scraper $IMAGE_ID:latest
          docker tag page_scraper $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ github.sha }}

      # TODO: Consider running helm upgrade

      - name: Deploy web_server
        uses: actions-hub/kubectl@v1.33.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get rollout restart deployment/web-server

      - name: Deploy page_scraper
        uses: actions-hub/kubectl@v1.33.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get rollout restart deployment/page-scraper
