name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run -ws --if-present test

      - name: Build web_server image
        run: |
          docker build -t web_server \
            --build-arg="VERSION=${{ github.sha }}" \
            --build-arg="WORKSPACE=web_server" \
            --build-arg="WORKSPACE_DIR=web_server" \
            --label "runnumber=${GITHUB_RUN_ID}" \
            -f Dockerfile \
            .

      - name: Build page_scraper image
        run: |
          docker build -t page_scraper \
            --build-arg="VERSION=${{ github.sha }}" \
            --build-arg="WORKSPACE=page_scraper" \
            --build-arg="WORKSPACE_DIR=crawlers/page_scraper" \
            --label "runnumber=${GITHUB_RUN_ID}" \
            -f Dockerfile \
            .
