name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint root project
        run: npm run lint

      - name: Build all workspaces
        run: npm run build --workspaces
